### ISSUE TITLE
Won't install via pip

### ISSUE THREAD

**Issue by daroot** [basho/python-erlastic#2]
Using python 2.7:

```
; virtualenv erlastic-broken
New python executable in erlastic-broken/bin/python2.7
Also creating executable in erlastic-broken/bin/python
Installing setuptools, pip, wheel...done.
; ./erlastic-broken/bin/pip install basho-erlastic
Collecting basho-erlastic
  Using cached basho-erlastic-2.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-nB7_vU/basho-erlastic/setup.py", line 5, in <module>
        from erlastic import __version__ as version
      File "erlastic/__init__.py", line 6, in <module>
        from erlastic.codec import ErlangTermDecoder, ErlangTermEncoder
      File "erlastic/codec.py", line 4, in <module>
        import six
    ImportError: No module named six
```

python 3.5 gives a similar output.

**Comment by lukebakken** [comment]
Fixed in da4f1cf51d6b72de79431e38c67f1f36b0bfbc3f
